#!/usr/bin/env bash
# servers are the piece of software generating and serving HTML Pages
# Installing nginx on web-01

apt-get update -y
apt-get install nginx -y
sudo ufx allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
