#!/usr/bin/env bash
# a bash script runs nginx as nginx user

nginx_conf="/etc/nginx/nginx.conf"

# create nginx user
sudo adduser --system --no-create-home --disabled-login --group nginx


pkill apache2
chown nginx:nginx $nginx_conf
chmod 777 /etc/nginx/nginx.conf
# set port 8080 listening port if not listening to port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
